### PR TITLE
Russian Localization: Translate all strings

### PR DESCRIPTION
**Pull request by Vladsg**
Russian Localization: Translate all strings. Wait update.

### CODE REVIEW

**Comment by azeier** [comment]
Can you rebase your changes on master again? I just force pushed something.

**Comment by Vladsg** [comment]
How? Create a new pull request?
P.S I do not often use GitHub

**Comment by azeier** [comment]
I can do it later, don't worry :). Let me know when this has all the translations (I'm also fine merging partials for now).

**Comment by Vladsg** [comment]
cc174b1 I update localization. Now all strings translate.

**Comment by azeier** [comment]
:+1:
Merged as https://github.com/HearthSim/HDT-Localization/commit/be18fde1f50f45c2208ffd93aa05b48ed7b658b0

**Pull request closed without merging**
