### PR TITLE
Add translation after Journey to Un'goro

### PR DESCRIPTION
**Pull request by milkshake-HS**
Add translation after Journey to Un'goro.
大魔境ウンゴロ以降の訳の追加

This translation is based on automatic translation by "ResX Resource Manager"
and some words are translated manually.
ResX Resource Managerを用いた自動翻訳をもとに、
手動で修正を加えています。

### CODE REVIEW

**Comment by milkshake-HS** [comment]
matanaki, I agree your opinion, and fix some translation. 
I would like you to check this.
matankiの意見を取り入れたので確認してほしいです。

**Comment by matanki153** [comment]
milkshake-HS, I've checked and it would be ok.
確認しました。特に問題がないと考えます。

**Comment by azeier** [comment]
Assuming the merge conflict is trivial, good to merge?

**Comment by azeier** [comment]
I have not actually looked into what exactly the reason or the conflict is - if there is no overlaps with #73 I can probably find a way to merge it regardless.

Looking closer, I guess this contains #73 now? So that one can be closed?

If you know how, can you fixup the commits in this one into 2-3? It's fine if not, I can take care of that too.

**Comment by milkshake-HS** [comment]
Yes, this contains #73 now, so it can be closed. 
I don't know how to fix up he commits in this one into 2-3.
I would like you to take care of that.

**Pull request merged**
