### PR TITLE
Ukrainian translation (complete)

### PR DESCRIPTION
**Pull request by olloff**
As title says.
Translation is full but unrevised (by ru-RU only), because I don't have Windows SDK and, therefore resgen.exe to compile resource files. 
If someone could advice me how to compile those without Windows SDK, I'll be grateful.

Cheers, хлопці!

### CODE REVIEW

**Comment by riQQ** [comment]
Maybe using the Mono resgen works: https://linux.die.net/man/1/resgen.

**Comment by riQQ** [comment]
Maybe using the Mono resgen works: https://linux.die.net/man/1/resgen.

**Comment by olloff** [comment]
Thanks, @riQQ, I wasn't aware of that.
But either I'm doing something wrong, its not working way I thought it would be.

Using mono resgen you advised:
```
> resgen /compile D:\projects\HDT-Localization\Strings.uk.resx,HearthstoneDeckTracker.resources.dll
Error: Unknown format in file C:\Users\olloff\HearthstoneDeckTracker.resources.dll

> resgen /compile D:\projects\HDT-Localization\Strings.uk.resx
Read in 878 resources from 'D:\projects\HDT-Localization\Strings.uk.resx'
Writing resource file...  Done.
>mv D:\projects\HDT-Localization\Strings.uk.resources D:\projects\HDT-Localization\HearthstoneDeckTracker.resources.dll 
```

Next I'm trying to replace existing resource file by modified one (in my case - pt-PT). HDT does start without errors, but nothing happens when I'm trying to use Portugal in language selector.
That really annoys me, do I need to build whole app to make change to resource files?

**Comment by azeier** [comment]
Yes, currently to see your changes you need to build HDT and disable it automatically pulling them from this repo ([by deleting these lines](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Hearthstone%20Deck%20Tracker.csproj#L1530-L1531)).

**Comment by olloff** [comment]
Thanks for make it clear.
Sadly, its not an option for me for now, could I ask any of you to make a build for me so I can review changes before they go live?

**Comment by azeier** [comment]
Here you go :) https://github.com/azeier/HDT-Test/releases/tag/v1.1.6.1-uk

**Comment by olloff** [comment]
uk translation should be considered as complete now, still there are issues, tho.

Please, accept this alongside with https://github.com/HearthSim/Hearthstone-Deck-Tracker/pull/3109

**Pull request merged**
