### PR TITLE
french translation

### PR DESCRIPTION
**Pull request by bmichotte**
still WIP

### CODE REVIEW

**Comment by Rekho** [comment]
Hi ! I'm really motivated to translate all the program into french langage but I don't know how to do. GitHub is really new for me I don't understand how it works. Can you help me ?

**Comment by Corellien** [comment]
Hello, I can help to translate too, if you want.

**Comment by bmichotte** [comment]
I'm very busy working on hstracker right now, so feel free to explain to let @Rekho and @Corellien continue the translation :)

**Comment by Corellien** [comment]
Thanks.
I saw the initial translation document you showed in your comment of the 27th September, @bmichotte.
I just have one question about the underscore in the translation. Is it for the keyboard shortcuts? 
And I need a way to edit the file... If it can be as simple as it.

**Comment by fdela** [comment]
French translation has been merged now, so this issue can be closed.

**Pull request closed without merging**
