### PR TITLE
Add brazilian portuguese translation

### PR DESCRIPTION
**Pull request by xm4rc0sx**

### CODE REVIEW

**Comment by azeier** [comment]
On the first glance it doesn't look like there are very many differences (any?) to the pt-PT translation. Is this worth adding as another language that needs maintenance?

**Comment by xm4rc0sx** [comment]
It's up to you

**Comment by azeier** [comment]
Are there significant differences in the translation?

If not, would you be willing to update the missing ones in pt-PT instead?

**Comment by xm4rc0sx** [comment]
some words have a different meaning

[example](https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2836#issuecomment-249426282)

**Comment by azeier** [comment]
Fair enough :).

**Pull request merged**
