### PR TITLE
Add Korean translation

### PR DESCRIPTION
**Pull request by bookman1209**
Still WIP

TODO
- Fill missing values
- Handle underscore(_) character
- Do context checking
- Do double-checking

### CODE REVIEW

**Comment by bookman1209** [comment]
Translation is almost done, so I want to build HDT with this koKR translation and check whether it is good or not.
To do this, I tried to build HDT with myself, but it keeps showing an error.
Following is my trial:

 - Using Microsoft Visual Studio Premium 2013
 - Using msbuild 12.0
 - Build Step
   1. $ git clone https://github.com/hearthsim/Hearthstone-Deck-Tracker
   2. run bootstrap.bat
   3. copy my Strings.ko-KR.resx file into `Hearthstone-Deck-Tracker/HDT-Localization` and `Hearthstone-Deck-Tracker/Hearthstone Deck Tracker/Properties`.
   4. run `Hearthstone-Deck-Tracker/Hearthstone Deck Tracker.sln` with MSVS
   5. in MSVS, click on 'build solution'
   6. 611 errors occured. Most are from 'HearthMirror', 'HearthDb', 'HSReplay' projects. Errors are like 'missing semicolon', 'class, struct or interface member declaration has wrong '(' token.'
 - I tried to build in command line with 'msbuild.exe' but it gives the same result.

Is there anything I am missing?

**Comment by jindaxia** [comment]
@bookman1209  try to use VS 2015 and .net 4.5

**Comment by bookman1209** [comment]
It worked! Thx :)

**Comment by azeier** [comment]
What's the status on this? :)

**Comment by azeier** [comment]
Sorry for my delay on this too (it was not on purpose, I swear :P)

Here's a build for you to check out: https://github.com/azeier/HDT-Test/releases/tag/v1.1.6.1

**Comment by bookman1209** [comment]
I think everything seems to be OK, except the text added after Mean Streets of Gadgetzan. I'll add translations for those. Should I make a new PR or just open this PR again and add commits?
Also, some text are translated but displayed with delay. Is it intended or a bug? For example, for the drop-down menus in  _Option > Tracker > Stats > Display_ selectable fields are displayed in English at first, but if user clicks the field, they are displayed in Korean correctly. Below pictures are provided to help understanding.

**Picture 1. When user sees menu at first**
before

**Picture 2. When user clicks the drop-down field**
intermediate

**Picture 3. When user selects the field value**
after

This happens in _Option > Trancker > Stats > Display_ and _Option > Tracker > Design > Theme_

**Pull request merged**
